name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.0
        with:
          working_directory: ''
          tfsec_args: --soft-fail --concise-output --include-passed --force-all-dirs --minimum-severity MEDIUM
          github_token: ${{ github.token }}
