name: iac-scan
on:
  pull_request:
jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Get changed dir-names
        id: changed-files
        uses: hi-artem/changed-files@main
        with:
          dir_names: "true"
          json: "true"
          max_fetch_depth: "2147483647"
          files: |
            terraform/**
      - name: List all changed files
        run: |
          echo '${{ steps.changed-files.outputs.all_changed_files }}'
      - id: set-matrix
        run: echo "matrix={\"files\":${{ steps.changed-files.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  tfsec:
    name: IaC Scan with tfsec
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          tfsec_args: --custom-check-dir .tfsec
          soft_fail_commenter: true
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          working_directory: ${{  matrix.files }}
