name: tfsec
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR checker
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          github_token: ${{ github.token }}
          working_directory: ''
          tfsec_args: --concise-output --debug --config-file=.tfsec.yml --custom-check-dir=.tfsec --force-all-dirs
