name: tfsec-pr-commenter
on:
  pull_request:
jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      actions: read
      security-events: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: --force-all-dirs
          github_token: ${{ github.token }}
          soft_fail_commenter: true
